// <auto-generated />
using System;
using FullControlFootball.Infrastructure.Percistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullControlFootball.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CareerSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentSeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("GameEdition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MainClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MainClubId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("career_saves", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DefaultCompetitionId");

                    b.HasIndex("ExternalSource", "ExternalId");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.ClubPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SquadRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ClubId", "PlayerId", "IsActive");

                    b.ToTable("club_players", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsContinental")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDomestic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ExternalSource", "ExternalId");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SeasonCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonCompetitionId");

                    b.HasIndex("SeasonCompetitionId", "SnapshotDateUtc");

                    b.ToTable("competition_standings", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionStandingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClubNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("CompetitionStandingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int?>("FinalStatus")
                        .HasColumnType("integer");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Played")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SaveClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CompetitionStandingId");

                    b.HasIndex("SaveClubId");

                    b.HasIndex("CompetitionStandingId", "Position")
                        .IsUnique();

                    b.ToTable("competition_standing_rows", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionTopAssist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClubNameSnapshot")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SaveClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SavePlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SaveClubId");

                    b.HasIndex("SavePlayerId");

                    b.HasIndex("SeasonCompetitionId");

                    b.HasIndex("SeasonCompetitionId", "SnapshotDateUtc", "Position");

                    b.ToTable("competition_top_assists", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionTopScorer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClubNameSnapshot")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SaveClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SavePlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SaveClubId");

                    b.HasIndex("SavePlayerId");

                    b.HasIndex("SeasonCompetitionId");

                    b.HasIndex("SeasonCompetitionId", "SnapshotDateUtc", "Position");

                    b.ToTable("competition_top_scorers", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FaceImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KnownAs")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("NationalityCountryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OverallBase")
                        .HasColumnType("integer");

                    b.Property<int?>("PotentialBase")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredFoot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryPositions")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NationalityCountryId");

                    b.HasIndex("ExternalSource", "ExternalId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SaveClub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareerSaveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClubNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUserClub")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerSaveId");

                    b.HasIndex("ClubId");

                    b.HasIndex("CareerSaveId", "ClubId")
                        .IsUnique();

                    b.ToTable("save_clubs", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SavePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("CareerSaveId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentClubId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<int?>("OverallCurrent")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("PotentialCurrent")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryPositionSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerSaveId");

                    b.HasIndex("CurrentClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CareerSaveId", "PlayerId")
                        .IsUnique();

                    b.ToTable("save_players", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareerSaveId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerSaveId");

                    b.HasIndex("CareerSaveId", "Number")
                        .IsUnique();

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SeasonCompetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareerSaveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsUserParticipating")
                        .HasColumnType("boolean");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerSaveId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CountryId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonId", "CompetitionId")
                        .IsUnique();

                    b.ToTable("season_competitions", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.TransferTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CareerSaveId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FromClubNameSnapshot")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("FromSaveClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("SavePlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToClubNameSnapshot")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("ToSaveClubId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransferWindowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerSaveId");

                    b.HasIndex("FromSaveClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SavePlayerId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ToSaveClubId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransferWindowId");

                    b.ToTable("transfer_transactions", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.TransferWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareerSaveId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerSaveId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonId", "Name")
                        .IsUnique();

                    b.ToTable("transfer_windows", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreferredTheme")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.UserAuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CareerSave", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Club", "MainClub")
                        .WithMany()
                        .HasForeignKey("MainClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.User", "User")
                        .WithMany("CareerSaves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainClub");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Club", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Competition", "DefaultCompetition")
                        .WithMany()
                        .HasForeignKey("DefaultCompetitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("DefaultCompetition");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.ClubPlayer", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Competition", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionStanding", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.SeasonCompetition", "SeasonCompetition")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeasonCompetition");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionStandingRow", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.CompetitionStanding", "CompetitionStanding")
                        .WithMany("Rows")
                        .HasForeignKey("CompetitionStandingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.SaveClub", "SaveClub")
                        .WithMany()
                        .HasForeignKey("SaveClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");

                    b.Navigation("CompetitionStanding");

                    b.Navigation("SaveClub");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionTopAssist", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SaveClub", "SaveClub")
                        .WithMany()
                        .HasForeignKey("SaveClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SavePlayer", "SavePlayer")
                        .WithMany()
                        .HasForeignKey("SavePlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SeasonCompetition", "SeasonCompetition")
                        .WithMany("TopAssists")
                        .HasForeignKey("SeasonCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");

                    b.Navigation("SaveClub");

                    b.Navigation("SavePlayer");

                    b.Navigation("SeasonCompetition");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionTopScorer", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SaveClub", "SaveClub")
                        .WithMany()
                        .HasForeignKey("SaveClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SavePlayer", "SavePlayer")
                        .WithMany()
                        .HasForeignKey("SavePlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SeasonCompetition", "SeasonCompetition")
                        .WithMany("TopScorers")
                        .HasForeignKey("SeasonCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");

                    b.Navigation("SaveClub");

                    b.Navigation("SavePlayer");

                    b.Navigation("SeasonCompetition");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Player", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.Country", "NationalityCountry")
                        .WithMany()
                        .HasForeignKey("NationalityCountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NationalityCountry");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SaveClub", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.CareerSave", "CareerSave")
                        .WithMany("SaveClubs")
                        .HasForeignKey("CareerSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerSave");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SavePlayer", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.CareerSave", "CareerSave")
                        .WithMany("SavePlayers")
                        .HasForeignKey("CareerSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.SaveClub", "CurrentClub")
                        .WithMany()
                        .HasForeignKey("CurrentClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerSave");

                    b.Navigation("CurrentClub");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Season", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.CareerSave", "CareerSave")
                        .WithMany("Seasons")
                        .HasForeignKey("CareerSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerSave");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SeasonCompetition", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.CareerSave", "CareerSave")
                        .WithMany("SeasonCompetitions")
                        .HasForeignKey("CareerSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Season", "Season")
                        .WithMany("SeasonCompetitions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerSave");

                    b.Navigation("Competition");

                    b.Navigation("Country");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.TransferTransaction", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.CareerSave", "CareerSave")
                        .WithMany("TransferTransactions")
                        .HasForeignKey("CareerSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.SaveClub", "FromSaveClub")
                        .WithMany()
                        .HasForeignKey("FromSaveClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.SavePlayer", "SavePlayer")
                        .WithMany()
                        .HasForeignKey("SavePlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.Season", "Season")
                        .WithMany("TransferTransactions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.SaveClub", "ToSaveClub")
                        .WithMany()
                        .HasForeignKey("ToSaveClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullControlFootball.Domain.Entities.TransferWindow", "TransferWindow")
                        .WithMany("Transactions")
                        .HasForeignKey("TransferWindowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CareerSave");

                    b.Navigation("FromSaveClub");

                    b.Navigation("Player");

                    b.Navigation("SavePlayer");

                    b.Navigation("Season");

                    b.Navigation("ToSaveClub");

                    b.Navigation("TransferWindow");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.TransferWindow", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.CareerSave", "CareerSave")
                        .WithMany("TransferWindows")
                        .HasForeignKey("CareerSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullControlFootball.Domain.Entities.Season", "Season")
                        .WithMany("TransferWindows")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerSave");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("FullControlFootball.Domain.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CareerSave", b =>
                {
                    b.Navigation("SaveClubs");

                    b.Navigation("SavePlayers");

                    b.Navigation("SeasonCompetitions");

                    b.Navigation("Seasons");

                    b.Navigation("TransferTransactions");

                    b.Navigation("TransferWindows");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.CompetitionStanding", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.Season", b =>
                {
                    b.Navigation("SeasonCompetitions");

                    b.Navigation("TransferTransactions");

                    b.Navigation("TransferWindows");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.SeasonCompetition", b =>
                {
                    b.Navigation("Standings");

                    b.Navigation("TopAssists");

                    b.Navigation("TopScorers");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.TransferWindow", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FullControlFootball.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("CareerSaves");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
